### ISSUE TITLE
black-screen on (arch) linux

### ISSUE THREAD

**Issue by verzil** [vshatskyi/black-screen#277]
## I can confirm that this works on arch linux.

however I ran into many problems when trying the program out. Using the standard method provided by the readme `npm start` or `npm run` I was experiencing problems with part of the code not getting permission from the os. Using `sudo` didn't work as well.

 after a bit of fiddling I just installed electron globally and did `electron .`, with electron-prebuild v0.37.2 and everything works. the commands work.
- vim doesn't work, there isn't a command feature for vim, therefore you cannot quit or write to file.
- tmux doesn't work, all characters a messed up inside tmux. 

**please note that I did run `npm run` to start the gulp server, which compiled all the typescript to javascript**

**Comment by tridentlead** [comment]
When I try to run it I get the error:

Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.37.2/docs

Error: Cannot find module '/home/***/Workspaces/black-screen'


Did you encounter this and how did you get around it

Archlinux > LNX Kernel 4.4.5-1

**Comment by verzil** [comment]
I actually did get the error before.
But I made a mistake of installing electron.... not electron-prebuild

Could you post the entire error log?

**Comment by clofresh** [comment]
FWIW, `npm i && npm start` worked fine for me on arch

**Comment by aubry74** [comment]
FYI Works fine on Ubuntu 16.04 as well (with few bugs, see below).
Node 6.0.0 installed using nvm, and using black-screen current head (712037f) on master branch.
`npm i && npm start` are working.
`npm run package` is working as well after adjusting the line in package.json : 

```
"package": "gulp build && electron-packager . \"$npm_package_productName\" --overwrite --platform=linux --arch=x64 --version=$npm_package_electronVersion --out='./dist' --icon='./icon.icns' --asar=true",
```

Finally it is possible to make a .deb installer with electron-installer-debian
`electron-installer-debian --src dist/Black\ Screen-linux-x64/ --dest dist/installers/ --arch amd64`

The few issues I noticed after playing with it few minutes were a bad keyboard layout mapping in vim (I have a Swiss-french keyboard and it switches to Swiss-german inside vim, works fine everywhere else), and also some input related stuff preventing `sudo` password from being correctly entered (this one is a bit more annoying but should not be too difficult to solve).

**Comment by PierreR** [comment]
Well in case it helps it fails to compile for me on `nixos` with:
```
npm ERR! peerinvalid The package typescript@2.0.0-dev.20160702 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.13.0 wants typescript@>=1.7.3

2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart black-screen@0.1.15
6 verbose unsafe-perm in lifecycle true
7 info black-screen@0.1.15 Failed to exec prestart script
8 verbose stack Error: black-screen@0.1.15 prestart: `npm install && npm run compile`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (/nix/store/2mlmjz8c1b2hsd1l3pc2kc09g73bz5h5-nodejs-4.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (/nix/store/2mlmjz8c1b2hsd1l3pc2kc09g73bz5h5-nodejs-4.3.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:821:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid black-screen@0.1.15
10 verbose cwd /home/pierre/projects/electron/black-screen
11 error Linux 4.4.13
12 error argv "/nix/store/2mlmjz8c1b2hsd1l3pc2kc09g73bz5h5-nodejs-4.3.1/bin/node" "/home/pierre/.nix-profile/bin/npm" "start"
13 error node v4.3.1
14 error npm  v2.14.12
15 error code ELIFECYCLE
16 error black-screen@0.1.15 prestart: `npm install && npm run compile`
16 error Exit status 1
17 error Failed at the black-screen@0.1.15 prestart script 'npm install && npm run compile'.
17 error This is most likely a problem with the black-screen package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm install && npm run compile
```
```
tsc --version
Version 1.8.10

tslint --version
3.13.0
```
Any idea ?

**Comment by vshatskyi** [comment]
It should work on Linux. Closing.
